/*
 * Author   Nerijus Ramanauskas <nerijus.ramanauskas@mocosel.org>,
 * Date     11/17/2013,
 * Revision 11/17/2013,
 *
 * Copyright 2013 Nerijus Ramanauskas.
 */

#include <Plain/Auxiliary.h>
#include <Plain/Compact.h>

MOCOSEL_PROTOTYPE(COMPACT_AND) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_ARRAY) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_DIFFERENCE) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_DO) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_IF) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_IS) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_OR) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_QUOTIENT) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_PRODUCT) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_REMAINDER) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_RETURN) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 1) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_PROTOTYPE(COMPACT_SUM) {
    MOCOSEL_ASSERT(VALUE != NULL);
    /* MOCOSEL_ERROR_SYSTEM. */
    if(VALUE == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_WORD_DOUBLE index = 0;
    MOCOSEL_WORD_DOUBLE length = MOCOSEL_MEASURE(NODE);
    /* MOCOSEL_ERROR_RUNTIME_WRONG_DATA. */
    if(length < 2) {
        return MOCOSEL_ERROR_RUNTIME_WRONG_DATA;
    }
    return 0;
}

MOCOSEL_WORD_DOUBLE COMPACT_EXPORT(struct MOCOSEL_SEGMENT* registry) {
    MOCOSEL_ASSERT(registry != NULL);
    /* MOCOSEL_ERROR_SYSTEM_WRONG_DATA. */
    if(registry == NULL) {
        return MOCOSEL_ERROR_SYSTEM_WRONG_DATA;
    }
    MOCOSEL_EXPORT("and", registry, &COMPACT_AND);
    MOCOSEL_EXPORT("array", registry, &COMPACT_ARRAY);
    MOCOSEL_EXPORT("difference", registry, &COMPACT_DIFFERENCE);
    MOCOSEL_EXPORT("do", registry, &COMPACT_DO);
    MOCOSEL_EXPORT("if", registry, &COMPACT_IF);
    MOCOSEL_EXPORT("is", registry, &COMPACT_IS);
    MOCOSEL_EXPORT("or", registry, &COMPACT_OR);
    MOCOSEL_EXPORT("quotient", registry, &COMPACT_QUOTIENT);
    MOCOSEL_EXPORT("product", registry, &COMPACT_PRODUCT);
    MOCOSEL_EXPORT("remainder", registry, &COMPACT_REMAINDER);;
    MOCOSEL_EXPORT("return", registry, &COMPACT_RETURN);
    MOCOSEL_EXPORT("sum", registry, &COMPACT_SUM);
    return 0;
}
