#
# Author   Nerijus Ramanauskas <nerijus.ramanauskas@mocosel.org>,
# Date     11/17/2013,
# Revision 11/17/2013,
#
# Copyright 2013 Nerijus Ramanauskas.
#

all:
	./Build.rb Text Markup

clean:
	rm -rf Markup/*
	find . -name *.DS_Store -exec rm -rf {} \;
	find . -name *.DS_Store.* -exec rm -rf {} \;
